package com.ssic.xinmin.pojo;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TeamExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table xm_team
     *
     * @mbggenerated Thu May 21 11:59:22 CST 2015
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table xm_team
     *
     * @mbggenerated Thu May 21 11:59:22 CST 2015
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table xm_team
     *
     * @mbggenerated Thu May 21 11:59:22 CST 2015
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xm_team
     *
     * @mbggenerated Thu May 21 11:59:22 CST 2015
     */
    public TeamExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xm_team
     *
     * @mbggenerated Thu May 21 11:59:22 CST 2015
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xm_team
     *
     * @mbggenerated Thu May 21 11:59:22 CST 2015
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xm_team
     *
     * @mbggenerated Thu May 21 11:59:22 CST 2015
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xm_team
     *
     * @mbggenerated Thu May 21 11:59:22 CST 2015
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xm_team
     *
     * @mbggenerated Thu May 21 11:59:22 CST 2015
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xm_team
     *
     * @mbggenerated Thu May 21 11:59:22 CST 2015
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xm_team
     *
     * @mbggenerated Thu May 21 11:59:22 CST 2015
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xm_team
     *
     * @mbggenerated Thu May 21 11:59:22 CST 2015
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xm_team
     *
     * @mbggenerated Thu May 21 11:59:22 CST 2015
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xm_team
     *
     * @mbggenerated Thu May 21 11:59:22 CST 2015
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table xm_team
     *
     * @mbggenerated Thu May 21 11:59:22 CST 2015
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("id like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("id not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andTeamNameIsNull() {
            addCriterion("team_name is null");
            return (Criteria) this;
        }

        public Criteria andTeamNameIsNotNull() {
            addCriterion("team_name is not null");
            return (Criteria) this;
        }

        public Criteria andTeamNameEqualTo(String value) {
            addCriterion("team_name =", value, "teamName");
            return (Criteria) this;
        }

        public Criteria andTeamNameNotEqualTo(String value) {
            addCriterion("team_name <>", value, "teamName");
            return (Criteria) this;
        }

        public Criteria andTeamNameGreaterThan(String value) {
            addCriterion("team_name >", value, "teamName");
            return (Criteria) this;
        }

        public Criteria andTeamNameGreaterThanOrEqualTo(String value) {
            addCriterion("team_name >=", value, "teamName");
            return (Criteria) this;
        }

        public Criteria andTeamNameLessThan(String value) {
            addCriterion("team_name <", value, "teamName");
            return (Criteria) this;
        }

        public Criteria andTeamNameLessThanOrEqualTo(String value) {
            addCriterion("team_name <=", value, "teamName");
            return (Criteria) this;
        }

        public Criteria andTeamNameLike(String value) {
            addCriterion("team_name like", value, "teamName");
            return (Criteria) this;
        }

        public Criteria andTeamNameNotLike(String value) {
            addCriterion("team_name not like", value, "teamName");
            return (Criteria) this;
        }

        public Criteria andTeamNameIn(List<String> values) {
            addCriterion("team_name in", values, "teamName");
            return (Criteria) this;
        }

        public Criteria andTeamNameNotIn(List<String> values) {
            addCriterion("team_name not in", values, "teamName");
            return (Criteria) this;
        }

        public Criteria andTeamNameBetween(String value1, String value2) {
            addCriterion("team_name between", value1, value2, "teamName");
            return (Criteria) this;
        }

        public Criteria andTeamNameNotBetween(String value1, String value2) {
            addCriterion("team_name not between", value1, value2, "teamName");
            return (Criteria) this;
        }

        public Criteria andRegionIdIsNull() {
            addCriterion("region_id is null");
            return (Criteria) this;
        }

        public Criteria andRegionIdIsNotNull() {
            addCriterion("region_id is not null");
            return (Criteria) this;
        }

        public Criteria andRegionIdEqualTo(String value) {
            addCriterion("region_id =", value, "regionId");
            return (Criteria) this;
        }

        public Criteria andRegionIdNotEqualTo(String value) {
            addCriterion("region_id <>", value, "regionId");
            return (Criteria) this;
        }

        public Criteria andRegionIdGreaterThan(String value) {
            addCriterion("region_id >", value, "regionId");
            return (Criteria) this;
        }

        public Criteria andRegionIdGreaterThanOrEqualTo(String value) {
            addCriterion("region_id >=", value, "regionId");
            return (Criteria) this;
        }

        public Criteria andRegionIdLessThan(String value) {
            addCriterion("region_id <", value, "regionId");
            return (Criteria) this;
        }

        public Criteria andRegionIdLessThanOrEqualTo(String value) {
            addCriterion("region_id <=", value, "regionId");
            return (Criteria) this;
        }

        public Criteria andRegionIdLike(String value) {
            addCriterion("region_id like", value, "regionId");
            return (Criteria) this;
        }

        public Criteria andRegionIdNotLike(String value) {
            addCriterion("region_id not like", value, "regionId");
            return (Criteria) this;
        }

        public Criteria andRegionIdIn(List<String> values) {
            addCriterion("region_id in", values, "regionId");
            return (Criteria) this;
        }

        public Criteria andRegionIdNotIn(List<String> values) {
            addCriterion("region_id not in", values, "regionId");
            return (Criteria) this;
        }

        public Criteria andRegionIdBetween(String value1, String value2) {
            addCriterion("region_id between", value1, value2, "regionId");
            return (Criteria) this;
        }

        public Criteria andRegionIdNotBetween(String value1, String value2) {
            addCriterion("region_id not between", value1, value2, "regionId");
            return (Criteria) this;
        }

        public Criteria andSchoolNameIsNull() {
            addCriterion("school_name is null");
            return (Criteria) this;
        }

        public Criteria andSchoolNameIsNotNull() {
            addCriterion("school_name is not null");
            return (Criteria) this;
        }

        public Criteria andSchoolNameEqualTo(String value) {
            addCriterion("school_name =", value, "schoolName");
            return (Criteria) this;
        }

        public Criteria andSchoolNameNotEqualTo(String value) {
            addCriterion("school_name <>", value, "schoolName");
            return (Criteria) this;
        }

        public Criteria andSchoolNameGreaterThan(String value) {
            addCriterion("school_name >", value, "schoolName");
            return (Criteria) this;
        }

        public Criteria andSchoolNameGreaterThanOrEqualTo(String value) {
            addCriterion("school_name >=", value, "schoolName");
            return (Criteria) this;
        }

        public Criteria andSchoolNameLessThan(String value) {
            addCriterion("school_name <", value, "schoolName");
            return (Criteria) this;
        }

        public Criteria andSchoolNameLessThanOrEqualTo(String value) {
            addCriterion("school_name <=", value, "schoolName");
            return (Criteria) this;
        }

        public Criteria andSchoolNameLike(String value) {
            addCriterion("school_name like", value, "schoolName");
            return (Criteria) this;
        }

        public Criteria andSchoolNameNotLike(String value) {
            addCriterion("school_name not like", value, "schoolName");
            return (Criteria) this;
        }

        public Criteria andSchoolNameIn(List<String> values) {
            addCriterion("school_name in", values, "schoolName");
            return (Criteria) this;
        }

        public Criteria andSchoolNameNotIn(List<String> values) {
            addCriterion("school_name not in", values, "schoolName");
            return (Criteria) this;
        }

        public Criteria andSchoolNameBetween(String value1, String value2) {
            addCriterion("school_name between", value1, value2, "schoolName");
            return (Criteria) this;
        }

        public Criteria andSchoolNameNotBetween(String value1, String value2) {
            addCriterion("school_name not between", value1, value2, "schoolName");
            return (Criteria) this;
        }

        public Criteria andTeamTypeIsNull() {
            addCriterion("team_type is null");
            return (Criteria) this;
        }

        public Criteria andTeamTypeIsNotNull() {
            addCriterion("team_type is not null");
            return (Criteria) this;
        }

        public Criteria andTeamTypeEqualTo(Integer value) {
            addCriterion("team_type =", value, "teamType");
            return (Criteria) this;
        }

        public Criteria andTeamTypeNotEqualTo(Integer value) {
            addCriterion("team_type <>", value, "teamType");
            return (Criteria) this;
        }

        public Criteria andTeamTypeGreaterThan(Integer value) {
            addCriterion("team_type >", value, "teamType");
            return (Criteria) this;
        }

        public Criteria andTeamTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("team_type >=", value, "teamType");
            return (Criteria) this;
        }

        public Criteria andTeamTypeLessThan(Integer value) {
            addCriterion("team_type <", value, "teamType");
            return (Criteria) this;
        }

        public Criteria andTeamTypeLessThanOrEqualTo(Integer value) {
            addCriterion("team_type <=", value, "teamType");
            return (Criteria) this;
        }

        public Criteria andTeamTypeIn(List<Integer> values) {
            addCriterion("team_type in", values, "teamType");
            return (Criteria) this;
        }

        public Criteria andTeamTypeNotIn(List<Integer> values) {
            addCriterion("team_type not in", values, "teamType");
            return (Criteria) this;
        }

        public Criteria andTeamTypeBetween(Integer value1, Integer value2) {
            addCriterion("team_type between", value1, value2, "teamType");
            return (Criteria) this;
        }

        public Criteria andTeamTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("team_type not between", value1, value2, "teamType");
            return (Criteria) this;
        }

        public Criteria andCaptainNameIsNull() {
            addCriterion("captain_name is null");
            return (Criteria) this;
        }

        public Criteria andCaptainNameIsNotNull() {
            addCriterion("captain_name is not null");
            return (Criteria) this;
        }

        public Criteria andCaptainNameEqualTo(String value) {
            addCriterion("captain_name =", value, "captainName");
            return (Criteria) this;
        }

        public Criteria andCaptainNameNotEqualTo(String value) {
            addCriterion("captain_name <>", value, "captainName");
            return (Criteria) this;
        }

        public Criteria andCaptainNameGreaterThan(String value) {
            addCriterion("captain_name >", value, "captainName");
            return (Criteria) this;
        }

        public Criteria andCaptainNameGreaterThanOrEqualTo(String value) {
            addCriterion("captain_name >=", value, "captainName");
            return (Criteria) this;
        }

        public Criteria andCaptainNameLessThan(String value) {
            addCriterion("captain_name <", value, "captainName");
            return (Criteria) this;
        }

        public Criteria andCaptainNameLessThanOrEqualTo(String value) {
            addCriterion("captain_name <=", value, "captainName");
            return (Criteria) this;
        }

        public Criteria andCaptainNameLike(String value) {
            addCriterion("captain_name like", value, "captainName");
            return (Criteria) this;
        }

        public Criteria andCaptainNameNotLike(String value) {
            addCriterion("captain_name not like", value, "captainName");
            return (Criteria) this;
        }

        public Criteria andCaptainNameIn(List<String> values) {
            addCriterion("captain_name in", values, "captainName");
            return (Criteria) this;
        }

        public Criteria andCaptainNameNotIn(List<String> values) {
            addCriterion("captain_name not in", values, "captainName");
            return (Criteria) this;
        }

        public Criteria andCaptainNameBetween(String value1, String value2) {
            addCriterion("captain_name between", value1, value2, "captainName");
            return (Criteria) this;
        }

        public Criteria andCaptainNameNotBetween(String value1, String value2) {
            addCriterion("captain_name not between", value1, value2, "captainName");
            return (Criteria) this;
        }

        public Criteria andCaptainPhoneIsNull() {
            addCriterion("captain_phone is null");
            return (Criteria) this;
        }

        public Criteria andCaptainPhoneIsNotNull() {
            addCriterion("captain_phone is not null");
            return (Criteria) this;
        }

        public Criteria andCaptainPhoneEqualTo(String value) {
            addCriterion("captain_phone =", value, "captainPhone");
            return (Criteria) this;
        }

        public Criteria andCaptainPhoneNotEqualTo(String value) {
            addCriterion("captain_phone <>", value, "captainPhone");
            return (Criteria) this;
        }

        public Criteria andCaptainPhoneGreaterThan(String value) {
            addCriterion("captain_phone >", value, "captainPhone");
            return (Criteria) this;
        }

        public Criteria andCaptainPhoneGreaterThanOrEqualTo(String value) {
            addCriterion("captain_phone >=", value, "captainPhone");
            return (Criteria) this;
        }

        public Criteria andCaptainPhoneLessThan(String value) {
            addCriterion("captain_phone <", value, "captainPhone");
            return (Criteria) this;
        }

        public Criteria andCaptainPhoneLessThanOrEqualTo(String value) {
            addCriterion("captain_phone <=", value, "captainPhone");
            return (Criteria) this;
        }

        public Criteria andCaptainPhoneLike(String value) {
            addCriterion("captain_phone like", value, "captainPhone");
            return (Criteria) this;
        }

        public Criteria andCaptainPhoneNotLike(String value) {
            addCriterion("captain_phone not like", value, "captainPhone");
            return (Criteria) this;
        }

        public Criteria andCaptainPhoneIn(List<String> values) {
            addCriterion("captain_phone in", values, "captainPhone");
            return (Criteria) this;
        }

        public Criteria andCaptainPhoneNotIn(List<String> values) {
            addCriterion("captain_phone not in", values, "captainPhone");
            return (Criteria) this;
        }

        public Criteria andCaptainPhoneBetween(String value1, String value2) {
            addCriterion("captain_phone between", value1, value2, "captainPhone");
            return (Criteria) this;
        }

        public Criteria andCaptainPhoneNotBetween(String value1, String value2) {
            addCriterion("captain_phone not between", value1, value2, "captainPhone");
            return (Criteria) this;
        }

        public Criteria andTeamDescIsNull() {
            addCriterion("team_desc is null");
            return (Criteria) this;
        }

        public Criteria andTeamDescIsNotNull() {
            addCriterion("team_desc is not null");
            return (Criteria) this;
        }

        public Criteria andTeamDescEqualTo(String value) {
            addCriterion("team_desc =", value, "teamDesc");
            return (Criteria) this;
        }

        public Criteria andTeamDescNotEqualTo(String value) {
            addCriterion("team_desc <>", value, "teamDesc");
            return (Criteria) this;
        }

        public Criteria andTeamDescGreaterThan(String value) {
            addCriterion("team_desc >", value, "teamDesc");
            return (Criteria) this;
        }

        public Criteria andTeamDescGreaterThanOrEqualTo(String value) {
            addCriterion("team_desc >=", value, "teamDesc");
            return (Criteria) this;
        }

        public Criteria andTeamDescLessThan(String value) {
            addCriterion("team_desc <", value, "teamDesc");
            return (Criteria) this;
        }

        public Criteria andTeamDescLessThanOrEqualTo(String value) {
            addCriterion("team_desc <=", value, "teamDesc");
            return (Criteria) this;
        }

        public Criteria andTeamDescLike(String value) {
            addCriterion("team_desc like", value, "teamDesc");
            return (Criteria) this;
        }

        public Criteria andTeamDescNotLike(String value) {
            addCriterion("team_desc not like", value, "teamDesc");
            return (Criteria) this;
        }

        public Criteria andTeamDescIn(List<String> values) {
            addCriterion("team_desc in", values, "teamDesc");
            return (Criteria) this;
        }

        public Criteria andTeamDescNotIn(List<String> values) {
            addCriterion("team_desc not in", values, "teamDesc");
            return (Criteria) this;
        }

        public Criteria andTeamDescBetween(String value1, String value2) {
            addCriterion("team_desc between", value1, value2, "teamDesc");
            return (Criteria) this;
        }

        public Criteria andTeamDescNotBetween(String value1, String value2) {
            addCriterion("team_desc not between", value1, value2, "teamDesc");
            return (Criteria) this;
        }

        public Criteria andTeamLogoIsNull() {
            addCriterion("team_logo is null");
            return (Criteria) this;
        }

        public Criteria andTeamLogoIsNotNull() {
            addCriterion("team_logo is not null");
            return (Criteria) this;
        }

        public Criteria andTeamLogoEqualTo(String value) {
            addCriterion("team_logo =", value, "teamLogo");
            return (Criteria) this;
        }

        public Criteria andTeamLogoNotEqualTo(String value) {
            addCriterion("team_logo <>", value, "teamLogo");
            return (Criteria) this;
        }

        public Criteria andTeamLogoGreaterThan(String value) {
            addCriterion("team_logo >", value, "teamLogo");
            return (Criteria) this;
        }

        public Criteria andTeamLogoGreaterThanOrEqualTo(String value) {
            addCriterion("team_logo >=", value, "teamLogo");
            return (Criteria) this;
        }

        public Criteria andTeamLogoLessThan(String value) {
            addCriterion("team_logo <", value, "teamLogo");
            return (Criteria) this;
        }

        public Criteria andTeamLogoLessThanOrEqualTo(String value) {
            addCriterion("team_logo <=", value, "teamLogo");
            return (Criteria) this;
        }

        public Criteria andTeamLogoLike(String value) {
            addCriterion("team_logo like", value, "teamLogo");
            return (Criteria) this;
        }

        public Criteria andTeamLogoNotLike(String value) {
            addCriterion("team_logo not like", value, "teamLogo");
            return (Criteria) this;
        }

        public Criteria andTeamLogoIn(List<String> values) {
            addCriterion("team_logo in", values, "teamLogo");
            return (Criteria) this;
        }

        public Criteria andTeamLogoNotIn(List<String> values) {
            addCriterion("team_logo not in", values, "teamLogo");
            return (Criteria) this;
        }

        public Criteria andTeamLogoBetween(String value1, String value2) {
            addCriterion("team_logo between", value1, value2, "teamLogo");
            return (Criteria) this;
        }

        public Criteria andTeamLogoNotBetween(String value1, String value2) {
            addCriterion("team_logo not between", value1, value2, "teamLogo");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeIsNull() {
            addCriterion("last_update_time is null");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeIsNotNull() {
            addCriterion("last_update_time is not null");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeEqualTo(Date value) {
            addCriterion("last_update_time =", value, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeNotEqualTo(Date value) {
            addCriterion("last_update_time <>", value, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeGreaterThan(Date value) {
            addCriterion("last_update_time >", value, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("last_update_time >=", value, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeLessThan(Date value) {
            addCriterion("last_update_time <", value, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("last_update_time <=", value, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeIn(List<Date> values) {
            addCriterion("last_update_time in", values, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeNotIn(List<Date> values) {
            addCriterion("last_update_time not in", values, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("last_update_time between", value1, value2, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("last_update_time not between", value1, value2, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andStatIsNull() {
            addCriterion("stat is null");
            return (Criteria) this;
        }

        public Criteria andStatIsNotNull() {
            addCriterion("stat is not null");
            return (Criteria) this;
        }

        public Criteria andStatEqualTo(Integer value) {
            addCriterion("stat =", value, "stat");
            return (Criteria) this;
        }

        public Criteria andStatNotEqualTo(Integer value) {
            addCriterion("stat <>", value, "stat");
            return (Criteria) this;
        }

        public Criteria andStatGreaterThan(Integer value) {
            addCriterion("stat >", value, "stat");
            return (Criteria) this;
        }

        public Criteria andStatGreaterThanOrEqualTo(Integer value) {
            addCriterion("stat >=", value, "stat");
            return (Criteria) this;
        }

        public Criteria andStatLessThan(Integer value) {
            addCriterion("stat <", value, "stat");
            return (Criteria) this;
        }

        public Criteria andStatLessThanOrEqualTo(Integer value) {
            addCriterion("stat <=", value, "stat");
            return (Criteria) this;
        }

        public Criteria andStatIn(List<Integer> values) {
            addCriterion("stat in", values, "stat");
            return (Criteria) this;
        }

        public Criteria andStatNotIn(List<Integer> values) {
            addCriterion("stat not in", values, "stat");
            return (Criteria) this;
        }

        public Criteria andStatBetween(Integer value1, Integer value2) {
            addCriterion("stat between", value1, value2, "stat");
            return (Criteria) this;
        }

        public Criteria andStatNotBetween(Integer value1, Integer value2) {
            addCriterion("stat not between", value1, value2, "stat");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table xm_team
     *
     * @mbggenerated do_not_delete_during_merge Thu May 21 11:59:22 CST 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table xm_team
     *
     * @mbggenerated Thu May 21 11:59:22 CST 2015
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}