package com.ssic.xinmin.pojo;

import java.util.Date;

public class Team {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xm_team.id
     *
     * @mbggenerated Thu May 21 11:59:22 CST 2015
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xm_team.team_name
     *
     * @mbggenerated Thu May 21 11:59:22 CST 2015
     */
    private String teamName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xm_team.region_id
     *
     * @mbggenerated Thu May 21 11:59:22 CST 2015
     */
    private String regionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xm_team.school_name
     *
     * @mbggenerated Thu May 21 11:59:22 CST 2015
     */
    private String schoolName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xm_team.team_type
     *
     * @mbggenerated Thu May 21 11:59:22 CST 2015
     */
    private Integer teamType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xm_team.captain_name
     *
     * @mbggenerated Thu May 21 11:59:22 CST 2015
     */
    private String captainName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xm_team.captain_phone
     *
     * @mbggenerated Thu May 21 11:59:22 CST 2015
     */
    private String captainPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xm_team.team_desc
     *
     * @mbggenerated Thu May 21 11:59:22 CST 2015
     */
    private String teamDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xm_team.team_logo
     *
     * @mbggenerated Thu May 21 11:59:22 CST 2015
     */
    private String teamLogo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xm_team.create_time
     *
     * @mbggenerated Thu May 21 11:59:22 CST 2015
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xm_team.last_update_time
     *
     * @mbggenerated Thu May 21 11:59:22 CST 2015
     */
    private Date lastUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xm_team.stat
     *
     * @mbggenerated Thu May 21 11:59:22 CST 2015
     */
    private Integer stat;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xm_team.id
     *
     * @return the value of xm_team.id
     *
     * @mbggenerated Thu May 21 11:59:22 CST 2015
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xm_team.id
     *
     * @param id the value for xm_team.id
     *
     * @mbggenerated Thu May 21 11:59:22 CST 2015
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xm_team.team_name
     *
     * @return the value of xm_team.team_name
     *
     * @mbggenerated Thu May 21 11:59:22 CST 2015
     */
    public String getTeamName() {
        return teamName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xm_team.team_name
     *
     * @param teamName the value for xm_team.team_name
     *
     * @mbggenerated Thu May 21 11:59:22 CST 2015
     */
    public void setTeamName(String teamName) {
        this.teamName = teamName == null ? null : teamName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xm_team.region_id
     *
     * @return the value of xm_team.region_id
     *
     * @mbggenerated Thu May 21 11:59:22 CST 2015
     */
    public String getRegionId() {
        return regionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xm_team.region_id
     *
     * @param regionId the value for xm_team.region_id
     *
     * @mbggenerated Thu May 21 11:59:22 CST 2015
     */
    public void setRegionId(String regionId) {
        this.regionId = regionId == null ? null : regionId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xm_team.school_name
     *
     * @return the value of xm_team.school_name
     *
     * @mbggenerated Thu May 21 11:59:22 CST 2015
     */
    public String getSchoolName() {
        return schoolName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xm_team.school_name
     *
     * @param schoolName the value for xm_team.school_name
     *
     * @mbggenerated Thu May 21 11:59:22 CST 2015
     */
    public void setSchoolName(String schoolName) {
        this.schoolName = schoolName == null ? null : schoolName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xm_team.team_type
     *
     * @return the value of xm_team.team_type
     *
     * @mbggenerated Thu May 21 11:59:22 CST 2015
     */
    public Integer getTeamType() {
        return teamType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xm_team.team_type
     *
     * @param teamType the value for xm_team.team_type
     *
     * @mbggenerated Thu May 21 11:59:22 CST 2015
     */
    public void setTeamType(Integer teamType) {
        this.teamType = teamType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xm_team.captain_name
     *
     * @return the value of xm_team.captain_name
     *
     * @mbggenerated Thu May 21 11:59:22 CST 2015
     */
    public String getCaptainName() {
        return captainName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xm_team.captain_name
     *
     * @param captainName the value for xm_team.captain_name
     *
     * @mbggenerated Thu May 21 11:59:22 CST 2015
     */
    public void setCaptainName(String captainName) {
        this.captainName = captainName == null ? null : captainName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xm_team.captain_phone
     *
     * @return the value of xm_team.captain_phone
     *
     * @mbggenerated Thu May 21 11:59:22 CST 2015
     */
    public String getCaptainPhone() {
        return captainPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xm_team.captain_phone
     *
     * @param captainPhone the value for xm_team.captain_phone
     *
     * @mbggenerated Thu May 21 11:59:22 CST 2015
     */
    public void setCaptainPhone(String captainPhone) {
        this.captainPhone = captainPhone == null ? null : captainPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xm_team.team_desc
     *
     * @return the value of xm_team.team_desc
     *
     * @mbggenerated Thu May 21 11:59:22 CST 2015
     */
    public String getTeamDesc() {
        return teamDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xm_team.team_desc
     *
     * @param teamDesc the value for xm_team.team_desc
     *
     * @mbggenerated Thu May 21 11:59:22 CST 2015
     */
    public void setTeamDesc(String teamDesc) {
        this.teamDesc = teamDesc == null ? null : teamDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xm_team.team_logo
     *
     * @return the value of xm_team.team_logo
     *
     * @mbggenerated Thu May 21 11:59:22 CST 2015
     */
    public String getTeamLogo() {
        return teamLogo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xm_team.team_logo
     *
     * @param teamLogo the value for xm_team.team_logo
     *
     * @mbggenerated Thu May 21 11:59:22 CST 2015
     */
    public void setTeamLogo(String teamLogo) {
        this.teamLogo = teamLogo == null ? null : teamLogo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xm_team.create_time
     *
     * @return the value of xm_team.create_time
     *
     * @mbggenerated Thu May 21 11:59:22 CST 2015
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xm_team.create_time
     *
     * @param createTime the value for xm_team.create_time
     *
     * @mbggenerated Thu May 21 11:59:22 CST 2015
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xm_team.last_update_time
     *
     * @return the value of xm_team.last_update_time
     *
     * @mbggenerated Thu May 21 11:59:22 CST 2015
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xm_team.last_update_time
     *
     * @param lastUpdateTime the value for xm_team.last_update_time
     *
     * @mbggenerated Thu May 21 11:59:22 CST 2015
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xm_team.stat
     *
     * @return the value of xm_team.stat
     *
     * @mbggenerated Thu May 21 11:59:22 CST 2015
     */
    public Integer getStat() {
        return stat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xm_team.stat
     *
     * @param stat the value for xm_team.stat
     *
     * @mbggenerated Thu May 21 11:59:22 CST 2015
     */
    public void setStat(Integer stat) {
        this.stat = stat;
    }
}