package com.ssic.xinmin.pojo;

import java.util.Date;

public class Users {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xm_users.id
     *
     * @mbggenerated Mon May 25 15:08:11 CST 2015
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xm_users.real_name
     *
     * @mbggenerated Mon May 25 15:08:11 CST 2015
     */
    private String realName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xm_users.identify_id
     *
     * @mbggenerated Mon May 25 15:08:11 CST 2015
     */
    private String identifyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xm_users.student_card
     *
     * @mbggenerated Mon May 25 15:08:11 CST 2015
     */
    private String studentCard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xm_users.brithday
     *
     * @mbggenerated Mon May 25 15:08:11 CST 2015
     */
    private Date brithday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xm_users.mobile_no
     *
     * @mbggenerated Mon May 25 15:08:11 CST 2015
     */
    private String mobileNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xm_users.user_image
     *
     * @mbggenerated Mon May 25 15:08:11 CST 2015
     */
    private String userImage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xm_users.guard_name
     *
     * @mbggenerated Mon May 25 15:08:11 CST 2015
     */
    private String guardName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xm_users.guard_mobile
     *
     * @mbggenerated Mon May 25 15:08:11 CST 2015
     */
    private String guardMobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xm_users.orgin
     *
     * @mbggenerated Mon May 25 15:08:11 CST 2015
     */
    private String orgin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xm_users.nation
     *
     * @mbggenerated Mon May 25 15:08:11 CST 2015
     */
    private String nation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xm_users.height
     *
     * @mbggenerated Mon May 25 15:08:11 CST 2015
     */
    private String height;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xm_users.weight
     *
     * @mbggenerated Mon May 25 15:08:11 CST 2015
     */
    private String weight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xm_users.pos
     *
     * @mbggenerated Mon May 25 15:08:11 CST 2015
     */
    private String pos;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xm_users.team_id
     *
     * @mbggenerated Mon May 25 15:08:11 CST 2015
     */
    private String teamId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xm_users.create_time
     *
     * @mbggenerated Mon May 25 15:08:11 CST 2015
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xm_users.last_update_time
     *
     * @mbggenerated Mon May 25 15:08:11 CST 2015
     */
    private Date lastUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xm_users.stat
     *
     * @mbggenerated Mon May 25 15:08:11 CST 2015
     */
    private Integer stat;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xm_users.id
     *
     * @return the value of xm_users.id
     *
     * @mbggenerated Mon May 25 15:08:11 CST 2015
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xm_users.id
     *
     * @param id the value for xm_users.id
     *
     * @mbggenerated Mon May 25 15:08:11 CST 2015
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xm_users.real_name
     *
     * @return the value of xm_users.real_name
     *
     * @mbggenerated Mon May 25 15:08:11 CST 2015
     */
    public String getRealName() {
        return realName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xm_users.real_name
     *
     * @param realName the value for xm_users.real_name
     *
     * @mbggenerated Mon May 25 15:08:11 CST 2015
     */
    public void setRealName(String realName) {
        this.realName = realName == null ? null : realName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xm_users.identify_id
     *
     * @return the value of xm_users.identify_id
     *
     * @mbggenerated Mon May 25 15:08:11 CST 2015
     */
    public String getIdentifyId() {
        return identifyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xm_users.identify_id
     *
     * @param identifyId the value for xm_users.identify_id
     *
     * @mbggenerated Mon May 25 15:08:11 CST 2015
     */
    public void setIdentifyId(String identifyId) {
        this.identifyId = identifyId == null ? null : identifyId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xm_users.student_card
     *
     * @return the value of xm_users.student_card
     *
     * @mbggenerated Mon May 25 15:08:11 CST 2015
     */
    public String getStudentCard() {
        return studentCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xm_users.student_card
     *
     * @param studentCard the value for xm_users.student_card
     *
     * @mbggenerated Mon May 25 15:08:11 CST 2015
     */
    public void setStudentCard(String studentCard) {
        this.studentCard = studentCard == null ? null : studentCard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xm_users.brithday
     *
     * @return the value of xm_users.brithday
     *
     * @mbggenerated Mon May 25 15:08:11 CST 2015
     */
    public Date getBrithday() {
        return brithday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xm_users.brithday
     *
     * @param brithday the value for xm_users.brithday
     *
     * @mbggenerated Mon May 25 15:08:11 CST 2015
     */
    public void setBrithday(Date brithday) {
        this.brithday = brithday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xm_users.mobile_no
     *
     * @return the value of xm_users.mobile_no
     *
     * @mbggenerated Mon May 25 15:08:11 CST 2015
     */
    public String getMobileNo() {
        return mobileNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xm_users.mobile_no
     *
     * @param mobileNo the value for xm_users.mobile_no
     *
     * @mbggenerated Mon May 25 15:08:11 CST 2015
     */
    public void setMobileNo(String mobileNo) {
        this.mobileNo = mobileNo == null ? null : mobileNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xm_users.user_image
     *
     * @return the value of xm_users.user_image
     *
     * @mbggenerated Mon May 25 15:08:11 CST 2015
     */
    public String getUserImage() {
        return userImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xm_users.user_image
     *
     * @param userImage the value for xm_users.user_image
     *
     * @mbggenerated Mon May 25 15:08:11 CST 2015
     */
    public void setUserImage(String userImage) {
        this.userImage = userImage == null ? null : userImage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xm_users.guard_name
     *
     * @return the value of xm_users.guard_name
     *
     * @mbggenerated Mon May 25 15:08:11 CST 2015
     */
    public String getGuardName() {
        return guardName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xm_users.guard_name
     *
     * @param guardName the value for xm_users.guard_name
     *
     * @mbggenerated Mon May 25 15:08:11 CST 2015
     */
    public void setGuardName(String guardName) {
        this.guardName = guardName == null ? null : guardName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xm_users.guard_mobile
     *
     * @return the value of xm_users.guard_mobile
     *
     * @mbggenerated Mon May 25 15:08:11 CST 2015
     */
    public String getGuardMobile() {
        return guardMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xm_users.guard_mobile
     *
     * @param guardMobile the value for xm_users.guard_mobile
     *
     * @mbggenerated Mon May 25 15:08:11 CST 2015
     */
    public void setGuardMobile(String guardMobile) {
        this.guardMobile = guardMobile == null ? null : guardMobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xm_users.orgin
     *
     * @return the value of xm_users.orgin
     *
     * @mbggenerated Mon May 25 15:08:11 CST 2015
     */
    public String getOrgin() {
        return orgin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xm_users.orgin
     *
     * @param orgin the value for xm_users.orgin
     *
     * @mbggenerated Mon May 25 15:08:11 CST 2015
     */
    public void setOrgin(String orgin) {
        this.orgin = orgin == null ? null : orgin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xm_users.nation
     *
     * @return the value of xm_users.nation
     *
     * @mbggenerated Mon May 25 15:08:11 CST 2015
     */
    public String getNation() {
        return nation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xm_users.nation
     *
     * @param nation the value for xm_users.nation
     *
     * @mbggenerated Mon May 25 15:08:11 CST 2015
     */
    public void setNation(String nation) {
        this.nation = nation == null ? null : nation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xm_users.height
     *
     * @return the value of xm_users.height
     *
     * @mbggenerated Mon May 25 15:08:11 CST 2015
     */
    public String getHeight() {
        return height;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xm_users.height
     *
     * @param height the value for xm_users.height
     *
     * @mbggenerated Mon May 25 15:08:11 CST 2015
     */
    public void setHeight(String height) {
        this.height = height == null ? null : height.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xm_users.weight
     *
     * @return the value of xm_users.weight
     *
     * @mbggenerated Mon May 25 15:08:11 CST 2015
     */
    public String getWeight() {
        return weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xm_users.weight
     *
     * @param weight the value for xm_users.weight
     *
     * @mbggenerated Mon May 25 15:08:11 CST 2015
     */
    public void setWeight(String weight) {
        this.weight = weight == null ? null : weight.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xm_users.pos
     *
     * @return the value of xm_users.pos
     *
     * @mbggenerated Mon May 25 15:08:11 CST 2015
     */
    public String getPos() {
        return pos;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xm_users.pos
     *
     * @param pos the value for xm_users.pos
     *
     * @mbggenerated Mon May 25 15:08:11 CST 2015
     */
    public void setPos(String pos) {
        this.pos = pos == null ? null : pos.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xm_users.team_id
     *
     * @return the value of xm_users.team_id
     *
     * @mbggenerated Mon May 25 15:08:11 CST 2015
     */
    public String getTeamId() {
        return teamId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xm_users.team_id
     *
     * @param teamId the value for xm_users.team_id
     *
     * @mbggenerated Mon May 25 15:08:11 CST 2015
     */
    public void setTeamId(String teamId) {
        this.teamId = teamId == null ? null : teamId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xm_users.create_time
     *
     * @return the value of xm_users.create_time
     *
     * @mbggenerated Mon May 25 15:08:11 CST 2015
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xm_users.create_time
     *
     * @param createTime the value for xm_users.create_time
     *
     * @mbggenerated Mon May 25 15:08:11 CST 2015
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xm_users.last_update_time
     *
     * @return the value of xm_users.last_update_time
     *
     * @mbggenerated Mon May 25 15:08:11 CST 2015
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xm_users.last_update_time
     *
     * @param lastUpdateTime the value for xm_users.last_update_time
     *
     * @mbggenerated Mon May 25 15:08:11 CST 2015
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xm_users.stat
     *
     * @return the value of xm_users.stat
     *
     * @mbggenerated Mon May 25 15:08:11 CST 2015
     */
    public Integer getStat() {
        return stat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xm_users.stat
     *
     * @param stat the value for xm_users.stat
     *
     * @mbggenerated Mon May 25 15:08:11 CST 2015
     */
    public void setStat(Integer stat) {
        this.stat = stat;
    }
}